language: java
jdk: openjdk11
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
    - secure: iIADjx3B/rNas5kfK15jWhWOKhYuK7YqECF9OsKnFmYCJ1ErYPtg5N1WQSaXElGNzX5yv+lmU2vcUVfIXgJ2UsZnNdqYg2g26t6nPi/ymXCsbQ9RgiK5fWlhpPij40zV9n+DKVe4jzh4kM8vwV495Rv8TK90aaoaAya6NBREy/ckQcYq3TUWFEHjwdnog9EZbAXrbRUyn9Ew3NV0HBEfA9joC9CKLrzeyceZ4/FukFLbahPo7qx4aPG5u9Zy6Gt0T+j7eZNtVqWBWMW0weKCqdxvGvotFfN17qq5tfl5zVieaITpHjw0nNMjJr/lBNBoxLxKTfUyYM0GtnlKP9468PmEPDp7x8EWXKmaN9vMz6eAh4AX5NhI+bShvf+3kP1mQU/D8ubzTXkA0nD79GZfYXoYXlI2EmyTBQqH3CiX3lNF0hnbs4uGfi8vs4A2cbSECUyhvAU1MK9S+Pb+dwhJ/VLDSl6QmXe1hWS/4wh3oii0A1MCYXSa1v9yXU1kwm7LzdbHacJC4oxWlPt6Zskx91VUHl0jU8Jo6EyNDHwgS8bZEzasR529nnw5bryze/qzlMmhuzxTSckofOOZ5jHkeXkPSJCv16LBJ9JdSA8ceOP+CJxWJuRWbq8xOsAtx7qV2ZMBQc9ugL7a1025umgKUn3x37HOAvJW3rFaWOS0JJ8=
    - secure: lXtOMGvck++1k/YmcVG9ifGH4WElDDgiCv2Sa//gLGv62wBUAkdaoyamNfmK1DKlg794M/KMfatVTq5CboGHK+orxMvVcVIM0wsUn5x/0McFjMvNu5MkXlxF8ayPZXr7ESDgqbXfnxXxAvPH80CSFg8tZAAqOmK5uK9C7KKyQo2GNULSiGtt5+QsV1jNZA+XMxXNbpqBUyvevjOd0pj2uAU5RGNPTTUtVK6Vvih/YrCJljF9eCwYSeIHFjazRVhDBbmKN7rSX3Lce6EzKojVNFSW11yZ2/GSWJcOmhvDx2x93j+1s5JMRDBbmZ2CE213WvFFThy9bojgphCu4SLoIl+dlSa+qWyLPFyfslzct60SCnhuup6H9aKTfAFUTXsI7oWHokIz0xsU9hBrcDRZKX/92N332S5RhtYmgr1DIoIXGdJrQGbuZOFU+arWKaY6pgmboQEKhVbazKi6CisFSFlIq+ycWW/4zb2nQ8j80eUj8B5lcuCHy3QmIYJvfv6vxm97xaq+Z3WIZwfhkMajUaFnkyprsTjLJraTorc2WbBbon1RlUK6x0+m3cQoIZmLJUdxXnBDvulLzGArh4cq/PKDCruL5Hif2XrzPhnyXL7GJzgHjRVAWM1uL9+aazeAfjDpgwfjAUBHUfmwuLmAo3BWnRoo1v51N08qExgw1ms=
deploy:
  provider: bintray
  file: pom.xml
  user: rodislav
  key:
    secure: PZeMrVZYD5hbN+RZ0Bglx5FH4O7PCeVVPdITGN/5bUaxA/UA8kIC1qnPZTDtVWinkUGypZW6Oe5bzHqcd/K2B7lrQ9f3UwBXRgTpYiHhyk4JcR1rGduyhY57GlrkD/F4h6xF1MEj7+1gsvvfmvxY5naIjDuJggc+U8IJv8wCMWttvKUkSgDJHjTFZP0X/LPa8tcLLZzWlCPejNmj2qNcFO79f8xHYNe4nmanei2WlpXuhJT33TJgSnw4bdpQxHXFzjiZQzltCytvP9J3BUM2QJwGNpj40XVeStGlCQ7o+m5xZWCPlanoEHWCynGFd74qsxqHlpeHSBQAck6+8dhLJNqoatygTz5OBEY5ILcxCg3EmcHJss9N/m7fnXJvq1bfKxmsH4Ut1HNtk96REu6H3ySLFBj37V6OEoDag4iIP749rXKuMIZ+kcHPUJlsK/6fIsMjBtqDA/dnW5C0hWAfvlM/a01VQipmC4UzIChWNaWXrDD1oHapxtnznHTB4SOq/IQutmAN/ByaJ5+6B4xkWpZH5CnhYdNYWyo0uY2a3NzOplf5fxZlk9HY8r6p8LIsoknqLPdQ2Ezt862DKcAn0W6sMXOEMqlgY/hr3rZl+2YMmbs+jQYmVHEdyeIwV1SxLDAv5dgYqO7tlLciehIg6CFJbGsNxc3RKpUsKKJFX1c=
  skip_cleanup: true
script:
- mvn --batch-mode release:prepare -Prelease -DskipTests
- mvn --batch-mode release:perform -Prelease -DskipTests
